title: miyasumas.github.io
lang: ja

remote_theme: zivhub/monophase

author:
  name: miyasumas
  url: https://miyasumas.github.io/

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
