title: miyasumas.github.io
description: 
google_analytics: 
show_downloads: false
github_username: miyasumas
author: miyasumas

#theme: minima
remote_theme: jekyll/minima

minima:
  skin: dark

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
