title: miyasumas.github.io
description: miyasumas.github.io

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links: 
    github: miyasumas
    qiita: miyasumas

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
